# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='Models',
  serialized_pb='\n\nuser.proto\x12\x06Models\"8\n\x1aKeyValuePair_String_String\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\t\"p\n\x04User\x12\r\n\x02Id\x18\x01 \x01(\x05:\x01\x30\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x15\n\x06\x41\x63tive\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x34\n\x08Metadata\x18\x04 \x03(\x0b\x32\".Models.KeyValuePair_String_String\" \n\x0bUserRequest\x12\x11\n\x06UserId\x18\x01 \x01(\x05:\x01\x30\x32;\n\x0bUserService\x12,\n\x07GetUser\x12\x13.Models.UserRequest\x1a\x0c.Models.UserB\x02H\x01')




_KEYVALUEPAIR_STRING_STRING = _descriptor.Descriptor(
  name='KeyValuePair_String_String',
  full_name='Models.KeyValuePair_String_String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Key', full_name='Models.KeyValuePair_String_String.Key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Value', full_name='Models.KeyValuePair_String_String.Value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=78,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='Models.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='Models.User.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Name', full_name='Models.User.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Active', full_name='Models.User.Active', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Metadata', full_name='Models.User.Metadata', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=80,
  serialized_end=192,
)


_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='Models.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserId', full_name='Models.UserRequest.UserId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=194,
  serialized_end=226,
)

_USER.fields_by_name['Metadata'].message_type = _KEYVALUEPAIR_STRING_STRING
DESCRIPTOR.message_types_by_name['KeyValuePair_String_String'] = _KEYVALUEPAIR_STRING_STRING
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST

class KeyValuePair_String_String(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEYVALUEPAIR_STRING_STRING

  # @@protoc_insertion_point(class_scope:Models.KeyValuePair_String_String)

class User(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USER

  # @@protoc_insertion_point(class_scope:Models.User)

class UserRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERREQUEST

  # @@protoc_insertion_point(class_scope:Models.UserRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\001')
# @@protoc_insertion_point(module_scope)
